# Generated by Django 2.2.7 on 2022-07-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='myself/')),
                ('details', models.TextField(max_length=500)),
                ('skills_deatils', models.TextField(max_length=300)),
                ('photograpy_skill', models.IntegerField(default=10)),
                ('naturalshot_skill', models.IntegerField(default=10)),
                ('selfiexpert_skill', models.IntegerField(default=10)),
                ('funnyshot_skill', models.IntegerField(default=10)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=400)),
                ('post_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider', models.ImageField(upload_to='Sliders/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until_date', models.DateField(blank=True, null=True)),
                ('payment', models.FloatField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal', models.EmailField(max_length=20, null=True)),
                ('payment', models.FloatField(default=0)),
                ('on_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=12)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='profile/')),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='ContestMaterial/')),
                ('post_on', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('love', models.ManyToManyField(blank=True, related_name='love', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=800)),
                ('demo_pic', models.ImageField(default='2.jpg', upload_to='Contest/')),
                ('start_on', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_on', models.DateField()),
                ('end_time', models.TimeField()),
                ('winner_ammount', models.FloatField()),
                ('contest_start', models.DateTimeField(blank=True)),
                ('contest_end', models.DateTimeField(blank=True)),
                ('contest_attends', models.ManyToManyField(blank=True, to='users.ContestMaterial')),
                ('joined', models.ManyToManyField(blank=True, related_name='joined', to=settings.AUTH_USER_MODEL)),
                ('post_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ManyToManyField(blank=True, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
