# Generated by Django 2.2.7 on 2022-07-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('p', 'Photo Grapher'), ('c', 'Contest Organizer')], max_length=12),
        ),
    ]
